language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -r test_project/requirements.txt
  - pip install -q -e . --use-mirrors
  - pip install selenium
before_script:
  - "pep8 --exclude=tests,migrations --ignore=E124,E128 not_eav"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python setup.py test
